apiVersion: apps/v1
kind: Deployment
metadata:
  name: saemea-app
  namespace: dev
  labels:
    app: saemea-app
    env: dev
spec:
  selector:
    matchLabels:
      app: saemea-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  replicas: 3
  template:
    metadata:
      labels:
        app: saemea-app
    spec:
      containers:
      - name: saemea-app
        image: {{ IMAGE_CONTAINER }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
      imagePullSecrets:
      - name: github-aquasaemea-dockerhub
#  docker.io/aquasaemea/saemea-app:11
#        livenessProbe:
#          httpGet:
#            path: /index.html
#            port: 3000
#            scheme: HTTP
#          initialDelaySeconds: 2
#          periodSeconds: 5
#          timeoutSeconds: 2
#        readinessProbe:
#          exec:
#            command:
#            - /bin/ls 
#            - /tmp/ready
#          initialDelaySeconds: 2
#          timeoutSeconds: 1
#        resources:
#          limits:
#            memory: "64Mi"
#            cpu: "500m"
#          requests:
#            memory: "32Mi"
#            cpu: "250m"
