name: SAEMEA APP 
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
      # comment
      
env:
   DOCKER_REPOSITORY: aquasaemea # name of Docker Hub ID
   IMAGE_NAME: saemea-app
   IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER

jobs:
  CI-Code:
    runs-on: ubuntu-20.04
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup pipeline enforcer
        uses: aquasecurity/pipeline-enforcer-action@main
        with:
          aqua-key: ${{ secrets.AQUA_KEY }}
          aqua-secret: ${{ secrets.AQUA_SECRET }}
          
      - name: Aqua code scanning(SCA,IaC and SAST)
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy fs --security-checks config,vuln,secret --sast .
          # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          # To enable SAST scanning, add: --sast
          # To enable npm/dotnet non-lock file scanning, add: --package-json / --dotnet-proj
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          GITHUB_TOKEN: ${{ github.token }}
          TRIVY_RUN_AS_PLUGIN: 'aqua'
          
  CI-Build:
    needs: CI-Code
    runs-on: ubuntu-20.04
      
    steps:   
   
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup pipeline enforcer
        uses: aquasecurity/pipeline-enforcer-action@main
        with:
          aqua-key: ${{ secrets.AQUA_KEY }}
          aqua-secret: ${{ secrets.AQUA_SECRET }}
  
      - name: Build application
        run: echo Application has been succesfully built 
        
      #https://github.com/marketplace/actions/build-and-push-docker-images
      #https://docs.docker.com/build/ci/github-actions/test-before-push/
      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2
      #- name: Build and push the Docker image
      #  uses: docker/build-push-action@v4
      #  with:
      #    tags: |
      #      $DOCKER_REPOSITORY/$IMAGE_NAME:latest
      #      $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
      #    push: true
      #    #cache-from: type=gha
      #    #cache-to: type=gha,mode=max
          
          
      - name: Build image container
        run: |
          sudo docker build -t $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
        
      - name: Login to Aqua Registry
        uses: docker/login-action@v1
        with:
          registry: registry.aquasec.com
          username: ${{ secrets.AQUA_REGISTRY_USERNAME }}
          password: ${{ secrets.AQUA_REGISTRY_PASS }}
          
      - name: Scanning container image
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4 scan --register --registry "CI/CD_andres_images" --host ${{ secrets.AQUA_HOST }} --local $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG --token ${{ secrets.AQUA_TOKEN }} --layer-vulnerabilities --no-verify --html > .github/workflows/scan-output.html
      # -e BUILD_JOB_NAME=$CI_JOB_NAME -e BUILD_URL=$CI_JOB_URL -e BUILD_NUMBER=$CI_JOB_ID
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Docker Login & Push
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG 
          docker tag $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG $DOCKER_REPOSITORY/$IMAGE_NAME:latest
          docker push $DOCKER_REPOSITORY/$IMAGE_NAME:latest 
        #docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
     
      - name: SBOM Generation
        run: |
          export BILLY_SERVER=https://billy.codesec.aquasec.com
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | sha256sum ; then
          echo "install.sh checksum failed"
          exit 1
          fi
          BINDIR="." sh install.sh
          rm install.sh install.sh.checksum
          ./billy generate \
            --access-token "${{ github.token }}" \
            --aqua-key "${{ secrets.AQUA_KEY }}" \
            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            --artifact-path "$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG"

            # The docker image name:tag of the newly built image
            # --artifact-path "my-image-name:${{ env.tag-version }}" 
            # OR the path to the root folder of your project. I.e my-repo/my-app 
            ## --artifact-path "${{env.MY_APP_ROOT}}"
            
  CD-Deploy_to_dev:
    #if: github.ref == 'refs/heads/development'
    needs: CI-Build
    runs-on: ubuntu-20.04
    
    steps: 
    
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup pipeline enforcer
        uses: aquasecurity/pipeline-enforcer-action@main
        with:
          aqua-key: ${{ secrets.AQUA_KEY }}
          aqua-secret: ${{ secrets.AQUA_SECRET }}
         
      - name: Setting K8s context
        uses: azure/k8s-set-context@v3
        with:
           method: kubeconfig
           kubeconfig: ${{ secrets.KUBECONFIG_ANDRES }}
           context: emea-aguisado-test
              
      - name: Deploying to Dev
        run: |
          export IMAGE_CONTAINER="docker.io/$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG"
          sed -e "s#{{ IMAGE_CONTAINER }}#$IMAGE_CONTAINER#g" "./manifests/dev/deployment.yaml" |
          kubectl apply -f -
          kubectl apply -f ./manifests/dev/service.yaml
      
      #### TESTING ############
      #- name: Deploying to Dev
      #  uses: Azure/k8s-artifact-substitute@v1
      #  with:
      #    manifests: |
      #       manifests/dev/deployment.yaml
      #       manifests/dev/service.yaml
      #    images: |
      #      "docker.io/aquasaemea/saemea-app:${{ github.run_number }}"
            
      #- name: Deploying to Dev
      #  uses: azure/k8s-deploy@v4 
      #  with:
      #     namespace: dev
      #     images: 'docker.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}' 
      #     manifests: |
      #        manifests/dev/deployment.yaml
      #        manifests/dev/service.yaml
          #kubernetes/ingress.yaml
          #'docker.io/$DOCKER_REPOSITORY/$IMAGE_NAME:${{ github.run_number }}'
          #docker.io/aquasaemea/insecure-bank-andres:${{ github.run_number }}
          #docker.io/aquasaemea/insecure-bank-andres:latest
          #docker.io/aquasaemea/insecure-bank-andres:90
          #docker.io/$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG  
     #https://github.com/marketplace/actions/kubernetes-set-context     
     #- name: Setting K8s context
     #  uses: azure/k8s-set-context@v3
     #  with:
     #     method: service-account
     #     k8s-url: https://emea-aguisado-test-dns-f0e6f17b.hcp.westeurope.azmk8s.io:443
     #     k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
     ################################
            
  CD-Deploy_to_stagging:
    #if: github.ref == 'refs/heads/stagging'
    needs: CD-Deploy_to_dev
    runs-on: ubuntu-20.04      
    
    steps:   
    
     - name: Checkout code
       uses: actions/checkout@v2
       
     - name: Setup pipeline enforcer
       uses: aquasecurity/pipeline-enforcer-action@main
       with:
          aqua-key: ${{ secrets.AQUA_KEY }}
          aqua-secret: ${{ secrets.AQUA_SECRET }}
     
     - name: Setting K8s context
       uses: azure/k8s-set-context@v3
       with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_ANDRES }}
          context: emea-aguisado-test
            
#https://nicwortel.nl/blog/2022/continuous-deployment-to-kubernetes-with-github-actions
#https://nicwortel.nl/blog/2020/simple-kubernetes-deployment-versioning
